/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    posts: Post;
    pages: Page;
    faq: Faq;
    media: Media;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'contact-info': ContactInfo;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Sitedeki hizmet sayfaları. Ana sayfadaki "Hizmetlerimiz" kartları ve üst menüdeki hizmet listesi buradan otomatik oluşur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Sayfanın en üstünde büyük başlık olarak ve hizmet kartlarında görünür.
   */
  title: string;
  /**
   * Ana sayfadaki hizmet kartında ve Google sonuçlarında görünen özet. En fazla 240 karakter.
   */
  excerpt?: string | null;
  /**
   * Hizmet kartında ve sayfanın üst bölümünde kullanılır. Önerilen ölçü: 1600 x 900 piksel (yatay).
   */
  coverImage?: (number | null) | Media;
  /**
   * Hizmetin detaylı anlatımı. Ara başlık, madde listesi ve bağlantı ekleyebilirsiniz.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL adresinde görünen kısa ad. Boş bırakılırsa başlıktan otomatik üretilir.
   */
  slug: string;
  /**
   * Hizmetlerin listelenme sırası. Küçük sayı önce gösterilir (1 en üstte). Emin değilseniz 100 bırakın.
   */
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Sitede kullanılan tüm fotoğraf ve belgeler. Bir görseli buraya bir kez yükleyip birden fazla sayfada kullanabilirsiniz.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Görselde ne olduğunu kısaca yazın. Görme engelli ziyaretçilere okunur ve Google için önemlidir — bu yüzden zorunludur.
   */
  alt: string;
  /**
   * Görselle ilgili kısa bir not. Sayfalarda gösterilmez; kütüphanede aramayı kolaylaştırır. Boş bırakabilirsiniz.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog yazıları ve duyurular. Sitedeki "Blog" sayfasında en yeniden eskiye doğru listelenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Yazının ana başlığı. Kısa ve açıklayıcı olması okunma oranını artırır.
   */
  title: string;
  /**
   * Blog kartlarında ve Google sonuçlarında görünen kısa metin. En fazla 300 karakter.
   */
  excerpt?: string | null;
  /**
   * Blog kartında ve sosyal medya paylaşımlarında kullanılır. Önerilen ölçü: 1600 x 900 piksel (yatay).
   */
  coverImage?: (number | null) | Media;
  /**
   * Yazının tam metni. Ara başlık, liste, bağlantı ve görsel ekleyebilirsiniz.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL adresinde görünen kısa ad. Boş bırakılırsa başlıktan otomatik üretilir.
   */
  slug: string;
  /**
   * Yazının sitede görünen tarihi. Listeleme sırası bu tarihe göre yapılır.
   */
  publishedDate: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Kurumsal ve yasal metin sayfaları: KVKK Aydınlatma Metni, Çerez Politikası, Başvuru Formu vb. Adresleri "site.com/sayfa-adi" biçimindedir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Sayfanın en üstünde görünen başlık ve menüdeki adı.
   */
  title: string;
  /**
   * Google arama sonuçlarında başlığın altında görünen açıklama. Boş bırakılırsa site geneli açıklama kullanılır.
   */
  excerpt?: string | null;
  /**
   * Sayfanın tam metni. Word veya benzeri bir programdan yapıştırdığınız metinler biçimlendirmesiyle birlikte gelir.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL adresinde görünen kısa ad. Boş bırakılırsa başlıktan otomatik üretilir.
   */
  slug: string;
  /**
   * İşaretliyse sayfa, üst menüdeki "Kurumsal" açılır listesinde görünür. Yalnızca adresi bilenlerin görmesini istiyorsanız işareti kaldırın.
   */
  showInCorporateMenu?: boolean | null;
  /**
   * Küçük sayı menüde daha üstte görünür.
   */
  menuOrder?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Sitedeki /sss sayfasında açılır-kapanır liste olarak gösterilen soru-cevaplar. Her kayıt bir soru demektir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * Ziyaretçinin tıklayacağı soru başlığı.
   */
  question: string;
  /**
   * Soruya verilen cevap. Kısa ve net tutmanız önerilir.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Soruların listelenme sırası. Küçük sayı önce gösterilir.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sitedeki iletişim formundan gönderilen mesajlar. Bu kayıtlar salt okunurdur; değiştirilemez, yalnızca okunup silinebilir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  /**
   * Yanıt vermek için bu adrese yazabilirsiniz.
   */
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  /**
   * Gönderen kişi formu doldururken KVKK metnini onayladı mı?
   */
  kvkkConsent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bu panele giriş yapabilen kişiler. Yeni bir çalışana erişim vermek için "Yeni Kullanıcı" deyip e-posta ve şifre belirleyin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Panelde ve kayıt listelerinde görünen isim.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Teknik ayar — yapay zekâ araçlarının siteyi güncellemesi için üretilen erişim anahtarları. İçerik düzenlemek için bu bölüme girmenize gerek yoktur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  services?: {
    /**
     * Allow clients to find services.
     */
    find?: boolean | null;
    /**
     * Allow clients to create services.
     */
    create?: boolean | null;
    /**
     * Allow clients to update services.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete services.
     */
    delete?: boolean | null;
  };
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete posts.
     */
    delete?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete pages.
     */
    delete?: boolean | null;
  };
  faq?: {
    /**
     * Allow clients to find faq.
     */
    find?: boolean | null;
    /**
     * Allow clients to create faq.
     */
    create?: boolean | null;
    /**
     * Allow clients to update faq.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete faq.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  contactSubmissions?: {
    /**
     * Allow clients to find contact-submissions.
     */
    find?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  contactInfo?: {
    /**
     * Allow clients to find contact-info global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update contact-info global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  slug?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  slug?: T;
  publishedDate?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  slug?: T;
  showInCorporateMenu?: T;
  menuOrder?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  kvkkConsent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  services?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  faq?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        update?: T;
      };
  contactSubmissions?:
    | T
    | {
        find?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  contactInfo?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Firma adı, logo ve Google/sosyal medya paylaşımlarında kullanılan varsayılan bilgiler. Buradaki değişiklikler sitenin tamamını etkiler.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Üst menüde, tarayıcı sekmesinde ve footer telif satırında görünür.
   */
  siteName: string;
  /**
   * Logonun altında görünen kısa tanıtım cümlesi.
   */
  tagline?: string | null;
  /**
   * Ticaret sicilindeki tam unvan. Arama motorlarına firma bilgisi olarak bildirilir; sayfalarda görünmez.
   */
  legalName?: string | null;
  /**
   * Üst menüde (beyaz zemin) kullanılır. Şeffaf arka planlı PNG veya SVG önerilir. Önerilen yükseklik: 56 piksel.
   */
  logo?: (number | null) | Media;
  /**
   * Footer lacivert zemin üzerinde kullanılır. Logonun beyaz / ters renkli versiyonunu yükleyin.
   */
  logoInverted?: (number | null) | Media;
  /**
   * Tarayıcı sekmesinde görünen küçük kare simge. Önerilen ölçü: 512 x 512 piksel.
   */
  favicon?: (number | null) | Media;
  defaultSeo?: {
    /**
     * Google sonuçlarında mavi bağlantı olarak görünen metin. 55-60 karakteri geçmemesi önerilir.
     */
    title?: string | null;
    /**
     * Google sonuçlarında başlığın altındaki gri açıklama. 150-160 karakter idealdir.
     */
    description?: string | null;
    /**
     * Site bağlantısı WhatsApp, LinkedIn veya Facebook’ta paylaşıldığında görünen görsel. Önerilen ölçü: 1200 x 630 piksel.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Üst bar, footer ve İletişim sayfası tek bir yerden — buradan — beslenir. Bir bilgiyi burada değiştirdiğinizde sitenin her yerinde güncellenir. Şu an temsili (örnek) değerler girilidir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  /**
   * Footer ve İletişim sayfasında olduğu gibi gösterilir.
   */
  addressLine?: string | null;
  /**
   * Google’a "bu firma nerede" bilgisini vermek için ayrıca istenir. Sayfada tek başına görünmez.
   */
  addressLocality?: string | null;
  postalCode?: string | null;
  /**
   * Ziyaretçiye gösterilen numara. Mobilde tıklanınca arama başlatır.
   */
  phone?: string | null;
  /**
   * Uluslararası formatta, boşluk ve parantez olmadan yazın. Örn: +905551112233
   */
  whatsapp?: string | null;
  /**
   * İletişim formundan gelen mesajların bildirileceği adres de budur.
   */
  email?: string | null;
  workingHours?: string | null;
  /**
   * Google Haritalar’da konumunuzu açın → Paylaş → "Haritayı yerleştir" → çıkan kodun içindeki src="..." adresini buraya yapıştırın. Şu an temsili bir konum girilidir.
   */
  mapEmbedUrl?: string | null;
  /**
   * Google Haritalar’da konuma sağ tıklayınca çıkan iki sayıdan ilki. Arama motorlarına konum bildirmek için kullanılır.
   */
  latitude?: number | null;
  /**
   * Sağ tıklayınca çıkan iki sayıdan ikincisi.
   */
  longitude?: number | null;
  social?: {
    facebook?: string | null;
    x?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  /**
   * "Yeni Link Ekle" ile satır ekleyin, soldaki tutamaçtan sürükleyerek sıralayın.
   */
  usefulLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  legalName?: T;
  logo?: T;
  logoInverted?: T;
  favicon?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  addressLine?: T;
  addressLocality?: T;
  postalCode?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  workingHours?: T;
  mapEmbedUrl?: T;
  latitude?: T;
  longitude?: T;
  social?:
    | T
    | {
        facebook?: T;
        x?: T;
        linkedin?: T;
        instagram?: T;
        youtube?: T;
      };
  usefulLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}